# Site settings
title: Carlos Muñoz
description: Senior Product Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Carlos Muñoz
user_description: Listening and understanding the problems from the root to give the best solution. Product-driven and customer care. Enthusiastic for learning new things and accepting new challenges. Sports and travels lover.
user_title: Senior Product Engineer
email: cmunozgar@gmail.com
twitter_username: cmunozgar
github_username:  cmunozgar

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
